apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl
  name: curl-pod-pod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - image: alpine/curl:3.14
        name: curl-image
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
