apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meet-stackit
  strategy: {}
  template:
    metadata:
      labels:
        app: meet-stackit
    spec:
      containers:
      - image: hoehne/meet-stackit:latest
        name: meet-stackit
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-service
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meet-stackit
  type: LoadBalancer
