apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-pod
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: meet-stackit
  template:
    metadata:
      labels:
        app: meet-stackit
    spec:
      containers:
      - image: hoehne/meet-stackit:latest
        name: meet-stackit
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 600Mi
            cpu: 2000m
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: actuator/health/livenessState
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: actuator/health/readinessState
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-service
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meet-stackit
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet-stackit-test
  name: meet-stackit-test
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: meet-stackit-test
  template:
    metadata:
      labels:
        app: meet-stackit-test
    spec:
      containers:
      - image: hoehne/meet-stackit-test:latest
        name: meet-stackit-test
        resources:
          requests:
            memory: 100Mi
            cpu: 150m
          limits:
            memory: 600Mi
            cpu: 500m
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
