apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-pod
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: meet-stackit
  template:
    metadata:
      labels:
        app: meet-stackit
    spec:
      containers:
      - image: hoehne/meet-stackit:latest
        name: meet-stackit
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.02"
          limits:
            memory: "500Mi"
            cpu: "0.05"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: actuator/health/livenessState
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: actuator/health/readinessState
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meet-stackit
  name: meet-stackit-service
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: meet-stackit
  type: LoadBalancer
