{
 "title": "Application Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "|                    |                                                     |\n|--------------------|-----------------------------------------------------|\n| Sample Application | http://193.148.167.139/hello?name=Put%20your%20name |\n| Metric Endpoint    | http://193.148.167.139/actuator/prometheus          |\n| Prometheus Server  | http://193.148.167.21:9090/graph                    |\n| git Repo           | https://github.com/JJDoneAway/meet-stackit          |"
   }
  },
  {
   "title": "Total Number of Service Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(GreetController_counter_total{application=\"STACKITDemoProject\"})"
    }
   ]
  },
  {
   "title": "av calls of the services per s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(GreetController_counter_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "av max latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "max(avg_over_time(GreetController_timer_seconds_max[5m]))"
    }
   ]
  },
  {
   "title": "Total Errorrate in %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(GreetController_error_total[10m])/rate(GreetController_counter_total[10m])) * 100"
    }
   ]
  },
  {
   "title": "Errorrate in % per Instance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(GreetController_error_total[10m])/rate(GreetController_counter_total[10m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}