management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,info,health
  metrics:
    tags:
      application: meet-stackit
    
server:
  tomcat:
    accesslog:
      buffered: false
      directory: /dev
      enabled: true
      file-date-format: ''
      prefix: stdout
      suffix: ''

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:msd38a3ec-mysql-0-0.data.eu01.onstackit.cloud}:49273/msd38a3ec
    username: ${DB_USERNAME}        
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j.bulkhead:
    configs:
        default:
            maxConcurrentCalls: 100
            maxWaitDuration: 500ms
    instances:
        backendDB:
            maxConcurrentCalls: 50

